<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lst</string>
	</array>
	<key>name</key>
	<string>Gams Listing</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>GAMS errors</string>
			<key>match</key>
			<string>^\*\*\*\*.*$
?</string>
			<key>name</key>
			<string>support.function.lst</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lst</string>
	<key>uuid</key>
	<string>aafdcaab-22a9-4ad5-9fe1-94bd7af0567c</string>
</dict>
</plist>
